INSERT INTO track_metadata (track_id, name, artist, duration_seconds, bpm, musical_key) VALUES
  ('Anyma, Argy, Son of Son - Voices In My Head.mp3', 'Voices In My Head', 'Anyma, Argy, Son of Son', 180, 112, '8A'),
  ('BLOND-ISH, ForgiveMeTommy! - We Like To Party - Rework.mp3', 'We Like To Party - Rework', 'BLOND-ISH, ForgiveMeTommy!', 197, 118, '9A'),
  ('Bedouin - Better Than This.mp3', 'Better Than This', 'Bedouin', 214, 124, '8B'),
  ('Betical - Do It Again.mp3', 'Do It Again', 'Betical', 231, 130, '11A'),
  ('Booka Shade, Eli & Fur, Einmusik - To the Sea - Einmusik Remix.mp3', 'To the Sea - Einmusik Remix', 'Booka Shade, Eli & Fur, Einmusik', 248, 136, '11B'),
  ('DJ T., Emanuel Satie - Funk On You - Emanuel Satie Remix.mp3', 'Funk On You - Emanuel Satie Remix', 'DJ T., Emanuel Satie', 265, 142, '2A'),
  ('Depeche Mode, Dixon - Cover Me - Dixon Remix.mp3', 'Cover Me - Dixon Remix', 'Depeche Mode, Dixon', 282, 112, '10B'),
  ('Echonomist, Avangart Tabldot, Alexandros Miaris, Mano Le Tough - Secret Places - Mano Le Tough Remix.mp3', 'Secret Places - Mano Le Tough Remix', 'Echonomist, Avangart Tabldot, Alexandros Miaris, Mano Le Tough', 299, 118, '5A'),
  ('Grooverick 548.m4a', 'Grooverick 548', 'Grooverick 548', 196, 124, '8A'),
  ('Helsloot - Let''s Pretend.mp3', 'Let''s Pretend', 'Helsloot', 213, 130, '9A'),
  ('Howling, Frank Wiedemann, RY X, Jimi Jules - Lover - Jimi Jules Lo-Fi Remix.mp3', 'Lover - Jimi Jules Lo-Fi Remix', 'Howling, Frank Wiedemann, RY X, Jimi Jules', 230, 136, '8B'),
  ('Liva K, Luch - Act A Fool.mp3', 'Act A Fool', 'Liva K, Luch', 247, 142, '11A'),
  ('MGMT, Thodoris Triantafillou, Mångata Projekt - Kids - Thodoris Triantafillou & Mångata Projekt Remix.mp3', 'Kids - Thodoris Triantafillou & Mångata Projekt Remix', 'MGMT, Thodoris Triantafillou, Mångata Projekt', 264, 112, '11B'),
  ('Marc DePulse, Rafael Cerato, Hadar, Malandra Jr. - Make a Show (Malandra Jr. Remix).mp3', 'Make a Show (Malandra Jr. Remix)', 'Marc DePulse, Rafael Cerato, Hadar, Malandra Jr.', 281, 118, '2A'),
  ('Mees Salomé, Joris Voorn, Celine Cairo - Fool''s Paradise - Joris Voorn Remix.mp3', 'Fool''s Paradise - Joris Voorn Remix', 'Mees Salomé, Joris Voorn, Celine Cairo', 298, 124, '10B'),
  ('Notre Dame - Nobody Told Me.mp3', 'Nobody Told Me', 'Notre Dame', 195, 130, '5A'),
  ('Oliver Koletzki, HVOB - Bones.mp3', 'Bones', 'Oliver Koletzki, HVOB', 212, 136, '8A'),
  ('Polo & Pan - The Mirror.mp3', 'The Mirror', 'Polo & Pan', 229, 142, '9A'),
  ('Raxon - The Cage Of Love.mp3', 'The Cage Of Love', 'Raxon', 246, 112, '8B'),
  ('Rem Siman - When You Need It - Radio Edit.mp3', 'When You Need It - Radio Edit', 'Rem Siman', 263, 118, '11A'),
  ('Rodriguez Jr. - Kids of Hula.mp3', 'Kids of Hula', 'Rodriguez Jr.', 280, 124, '11B'),
  ('Steve Angello, Modern Tales - Darkness In Me.mp3', 'Darkness In Me', 'Steve Angello, Modern Tales', 297, 130, '2A'),
  ('Tiësto, Mathame - Everlight.mp3', 'Everlight', 'Tiësto, Mathame', 194, 136, '10B'),
  ('Tiësto, Rose Ringed - Lethal Industry (Rose Ringed Remix).mp3', 'Lethal Industry (Rose Ringed Remix)', 'Tiësto, Rose Ringed', 211, 142, '5A'),
  ('Âme, Curses, Echonomist - Shadow Of Love - Echonomist Remix.mp3', 'Shadow Of Love - Echonomist Remix', 'Âme, Curses, Echonomist', 228, 112, '8A')
ON CONFLICT(track_id) DO UPDATE SET
  name = excluded.name,
  artist = excluded.artist,
  duration_seconds = excluded.duration_seconds,
  bpm = excluded.bpm,
  musical_key = excluded.musical_key;
